server:
  port : 8081

spring :
  datasource:
    #driver-class-name: oracle.jdbc.OracleDriver
    #url: jdbc:oracle:thin:@3.35.176.97:1521/xe
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@3.35.176.97:1521/xe

    username: root
    password: 1234

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  configuration:
    multiple-result-sets-enabled: false
    lazyLoadingEnabled: true
    aggressiveLazyLoading: false
    jdbc-type-for-null: varchar
    default-fetch-size: 500

  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.uos.cinemaseoul/**/**/



# 오라클 실행
# su -
# systemctl start oracle-xe
# systemctl status oracle-xe

# jar 실행
# java -Duser.timezone=Asia/Seoul -jar cinemaseoul-0.1.jar
# 서비스 설정
# cd /etc/systemd/system
# sudo vi server_start.service

#[Unit]
#Description=server start
#After=oracle.service (다음에 실행할 서비스)
#[Service]
#ExecStart=/bin/bash -c "exec java -jar [jar 파일 경로]/[jar파일].jar"
#[Install]
#WantedBy=multi-user.target

#sudo systemctl daemon-reload
#sudo systemctl enable [서비스 이름(server_start)].service
#sudo systemctl start [서비스 이름(server_start)].service

#아니면 nohup 해보기